theme: jekyll-theme-tactile

# urls
# your gh-pages url: https://username.github.io
url: https://lorenzonegri.github.io
# your repository name: /repository
baseurl: /Python-Labs

# defaults (to simplify front matter)
defaults:
  - scope:
      path: ""
    values:
      layout: default


